baseURL = "https://amather.github.io/"
languageCode = "en-us"
theme = "terminal"
publishDir = "docs"
pagination.pagerSize = 5

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true
    guessSyntax = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = false
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

[languages]
  [languages.en]
    title = "amather"
    subtitle = "C# engineering notes"
    keywords = "csharp, dotnet, programming"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "amather@blog:~$"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
